### ISSUE TITLE
Server Crashes When Editing Code

### ISSUE THREAD

**Issue by AuricFox** [AuricFox/Interview_Cards#2]
## Server Crashes When Editing Code

- **Issue**: When editing cards from the manage page, any code that is edited will cause the server to crash giving a 500 error.

- **Traceback**:
```
Traceback (most recent call last):
  File "C:\Users\sskit\OneDrive\Desktop\Interview_Cards\env\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sskit\OneDrive\Desktop\Interview_Cards\env\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sskit\OneDrive\Desktop\Interview_Cards\env\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sskit\OneDrive\Desktop\Interview_Cards\env\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\sskit\OneDrive\Desktop\Interview_Cards\app.py", line 59, in manage_flashcards_route
    data = database.view_allcards(category=None)
  File "C:\Users\sskit\OneDrive\Desktop\Interview_Cards\./src\database.py", line 205, in view_allcards
    question['code'] = code_data[1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AuricFox** [comment]
## [Patch] Server Crashes When Code Block Is Edited

- **Issue**: The server would crash after any edits to the code blocks in the flashcards were made. When a flashcard is edited the server performs a lookup to see if there is a `code_id` in the flashcard table. If there wasn't an id then the new data would be inserted into the Code table and the `cid` would be stored as `code_id` in the Flashcards table. If there was an id then the code in the Code table would be updated but a new `code_id` of 0 would be assigned. This would cause the server to cause because the code id cannot be accessed.

- **Solution**: A conditional statement was added to prevent the reassignment of a `code_id` if one already existed.

- **Old Code**:
```
# database.py line 277
current_code_id = c_code.lastrowid
flashcard_set = (category, question, answer, current_code_id, None, key)
```

- **Updated Code**:
```
current_code_id = c_code.lastrowid if current_code_id is None else current_code_id
flashcard_set = (category, question, answer, current_code_id, None, key)
```
